# Generated by Django 5.0.3 on 2024-03-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0002_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='categories',
        ),
    ]
