# Generated by Django 5.0.3 on 2024-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0005_alter_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
