# Generated by Django 5.0.3 on 2024-03-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0008_remove_product_image_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
