# Generated by Django 5.0.3 on 2024-03-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('jumia', '0010_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.business'),
        ),
    ]
