# Generated by Django 5.0.3 on 2024-04-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0011_type_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='Category',
        ),
        migrations.AddField(
            model_name='type',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jumia.product'),
        ),
    ]
