# Generated by Django 5.0.3 on 2024-04-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0016_remove_type_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='jumia.categories'),
        ),
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
