# Generated by Django 5.0.3 on 2024-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0018_remove_type_product_by_type_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
