# Generated by Django 5.0.3 on 2024-04-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0020_remove_type_contact_type_product_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
