# Generated by Django 5.0.6 on 2024-08-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0021_alter_type_image'),
        ('orders', '0010_payment_delete_address_remove_order_latitude_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.CreateModel(
            name='DirectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DirectOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('direct_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_order', to='orders.directorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_item', to='jumia.type')),
            ],
        ),
        migrations.AddIndex(
            model_name='directorder',
            index=models.Index(fields=['-created'], name='orders_dire_created_baf0e2_idx'),
        ),
    ]
