# Generated by Django 5.0.6 on 2024-08-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_payment_options_directorder_directorderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorderitem',
            name='direct_order',
        ),
        migrations.RemoveField(
            model_name='directorderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='DirectOrder',
        ),
        migrations.DeleteModel(
            name='DirectOrderItem',
        ),
    ]
