# Generated by Django 5.0.3 on 2024-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_options_remove_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
