# Generated by Django 5.0.3 on 2024-04-16 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
