# Generated by Django 5.0.3 on 2024-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_business_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
