# Generated by Django 5.0.6 on 2024-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
